const express = require('express');
const router = express.Router();

router.post('/advice', async (req, res) => {
  const { skinType, issues, location } = req.body;

  try {
    const activeLocation = location || 'Selected Coordinates';
    const weatherData = await fetchLiveWeather(activeLocation);

    const issueList = (issues || []).map(i => (i.name || '').toLowerCase());
    const hasAcne = issueList.some(i => i.includes('acne') || i.includes('breakout') || i.includes('blemish'));
    const hasDryness = issueList.some(i => i.includes('dry') || i.includes('dehydrat') || i.includes('flake'));
    const hasPigmentation = issueList.some(i => i.includes('pigment') || i.includes('spot') || i.includes('dark') || i.includes('melasma'));

    // 1. Atmospheric Stress Profile
    const atmosphericSummary = `At ${weatherData.temp}°F with ${weatherData.humidity}% relative humidity and a UV Index of ${weatherData.uvIndex} (${weatherData.uvLevel}), your skin is operating under active environmental stress. ${
      weatherData.temp > 80 ? 'Elevated temperatures increase micro-perspiration, diluting natural lipid protections.' : weatherData.temp < 55 ? 'Cooler air dampens micro-circulation, slowing down natural cellular turnover.' : 'Ambient temperature remains at a stable baseline.'
    }`;

    // 2. Barrier Integrity & Cellular Vulnerability
    let barrierAnalysis = `Your historical profile classification indicates a <strong>${skinType}</strong> barrier. `;
    if (weatherData.humidity < 40) {
      barrierAnalysis += `Because humidity is low (${weatherData.humidity}%), a steep moisture vapor pressure gradient pulls water directly out of your stratum corneum. This accelerates Transepidermal Water Loss (TEWL), leading to micro-fissures in your lipid matrix and heightened sensitivity.`;
    } else if (weatherData.humidity > 60) {
      barrierAnalysis += `With high ambient moisture (${weatherData.humidity}%), perspiration and sebum linger on the epidermis. For a ${skinType} profile, this creates an environment where dead skin cells bind together, clogging pores and fueling bacterial proliferation.`;
    } else {
      barrierAnalysis += `Moderate humidity maintains a balanced evaporation rate, minimizing extreme barrier shock.`;
    }

    // 3. Photoaging & Pigmentation Risk
    let photoagingRisk = `With a UV Index of ${weatherData.uvIndex}, solar radiation poses a direct threat to cellular DNA and collagen structures. `;
    if (weatherData.uvIndex >= 6) {
      photoagingRisk += `High-intensity UVA/UVB rays penetrate deep into the dermis, generating reactive oxygen species (free radicals) that break down collagen fibers and stimulate melanocytes. ${hasPigmentation ? 'Given your logged history of hyperpigmentation, this triggers an immediate defensive melanin surge, worsening dark spots.' : ''}`;
    } else {
      photoagingRisk += `Moderate radiation requires standard daily protection to prevent cumulative photo-damage.`;
    }

    // 4. Detailed Clinical Protocol & Routine Overrides
    let clinicalProtocol = `
      <li><strong>Environmental Shielding:</strong> Apply a broad-spectrum mineral SPF ${weatherData.uvIndex >= 6 ? '50+' : '30'} featuring non-nano zinc oxide and iron oxides to block both UV and High-Energy Visible (HEV) blue light.</li>
      <li><strong>Antioxidant Layering:</strong> Integrate an L-Ascorbic Acid (Vitamin C) serum into your morning sequence to neutralize free radicals generated by local UV exposure.</li>
    `;

    if (weatherData.humidity < 40 || hasDryness) {
      clinicalProtocol += `<li><strong>Barrier Recovery Protocol:</strong> Layer a low-molecular-weight hyaluronic acid serum onto damp skin, followed immediately by a ceramide-rich occlusive moisturizer to lock in hydration. Avoid foaming cleansers.</li>`;
    } else if (weatherData.humidity > 60 && hasAcne) {
      clinicalProtocol += `<li><strong>Clarifying Regimen Override:</strong> Swap creamy cleansers for a gentle 2% salicylic acid (BHA) wash. Use a lightweight, non-comedogenic gel hydrator to prevent oil-trapping.</li>`;
    } else {
      clinicalProtocol += `<li><strong>Maintenance Regimen:</strong> Maintain a gentle, pH-balanced cleansing routine supplemented with barrier-supporting peptides.</li>`;
    }

    res.json({ 
      success: true, 
      atmosphericSummary,
      barrierAnalysis,
      photoagingRisk,
      clinicalProtocol,
      weather: weatherData,
      location: activeLocation 
    });
  } catch (err) {
    console.error('Environmental advisor error:', err);
    res.status(500).json({ error: 'Failed to fetch environmental data.' });
  }
});

async function fetchLiveWeather(loc) {
  let lat = 48.85, lon = 2.35;
  if (typeof loc === 'string' && loc.includes('Lat:')) {
    const match = loc.match(/Lat:\s*([-\d.]+),\s*Lon:\s*([-\d.]+)/);
    if (match) {
      lat = parseFloat(match[1]);
      lon = parseFloat(match[2]);
    }
  }
  try {
    const res = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m&hourly=uv_index&timezone=auto`);
    const data = await res.json();
    const tempF = Math.round(((data.current?.temperature_2m ?? 21.5) * 9/5) + 32);
    const humidity = data.current?.relative_humidity_2m ?? 64;
    const uvIndex = Math.round(data.hourly?.uv_index?.[new Date().getHours()] ?? 5);
    return {
      uvIndex,
      uvLevel: uvIndex >= 8 ? 'Very High' : uvIndex >= 6 ? 'High' : 'Moderate',
      humidity,
      temp: tempF
    };
  } catch {
    return { uvIndex: 5, uvLevel: 'Moderate', humidity: 64, temp: 71 };
  }
}

module.exports = router;